### ISSUE TITLE
what's the key for settings or the button

### ISSUE THREAD

**Issue by JlJoJo2567** [poqbox/slotted-armor-hud#6]
I tried looking at the modrinth page and i could not find any direction on how to open/change settings.

**Comment by poqbox** [comment]
Sorry for the late reply. There is no dedicated button to access the mods settings, reason being that it would add to many keybinds when paired with more mods.
The method for accessing the settings is to use the [Mod Menu](https://modrinth.com/mod/modmenu) mod, which I highly recommend. It's a popular mod that  lists all of your installed mods in one place.
For more ways to configure the mod, you can find them at the bottom of the description under the "Configuration" section.
